### Arithmetics

In [7]:
8/5

1.6

In [8]:
8//5 #arithmetic division

1

In [9]:
print(3**2) #power

9


In [10]:
18 % 7 #modulo

4

In [11]:
##100$ after 7 years at 10%
100*(1+0.1)**7

194.87171000000012

### + operator on numeric and strings

In [12]:
2 +3  

5

In [13]:
'ab' + '_' + 'cd'

'ab_cd'

In [14]:
x = 5 # assign

In [15]:
x

5

In [16]:
desc = 'compound interest' # string
profitable = True  # boolean

In [17]:
type(desc) 

str

In [18]:
type(profitable)

bool

In [19]:
savings = 100
factor = 1.1
nyears = 7
result=savings*factor**nyears
print("I started with $" + str(savings) + " and now have $" + str(result) + ". Awesome!")

I started with $100 and now have $194.87171000000012. Awesome!


### type conversion

In [20]:
x = 10.1 ; print("the actual value of x is " + str(x))

the actual value of x is 10.1


In [21]:
float('3.1415')**2

9.86902225

In [22]:
crit = bool('True')
if crit :  print('this is true')

this is true


In [23]:
print("adding integers like " + str(5) + " to strings works")

adding integers like 5 to strings works


In [24]:
print( "multiplyng strings concatentates them " + ("Hey " * 2))

multiplyng strings concatentates them Hey Hey 


In [25]:
print(True+False)

1


In [26]:
print(False*False)

0


In [27]:
True*True

1

### List data type

In [28]:
l=[1.73, 1.74, -1.88]

In [29]:
l[0]

1.73

In [30]:
type(l)

list

In [31]:
fam=['aa', 1.10, 'bb', "a"*4, True] # list can contain any type

In [32]:
fam

['aa', 1.1, 'bb', 'aaaa', True]

In [33]:
fam2 =[['a',1],['b',2],['c',3]] # list of lists

In [34]:
fam2[0] #subsetting first list element

['a', 1]

In [35]:
fam2[-1] #last element

['c', 3]

In [36]:
fam2[-2] #before last

['b', 2]

In [37]:
fam2[0:2] #a sublist

[['a', 1], ['b', 2]]

In [38]:
fam[1:3] #subseting start:end  start el included, end el not included

[1.1, 'bb']

In [39]:
fam[:2] #first two elements

['aa', 1.1]

In [40]:
fam[-2:] #last two elements

['aaaa', True]

In [41]:
type(fam2)

list

#### higher dimensional list subsetting

In [42]:
x = [["a", "b", "c"], 
     ["d", "e", "f"], 
     ["g", "h", "i"]]

In [43]:
x[2][0]

'g'

In [44]:
x[2][:2] # a subset of a a specified row

['g', 'h']

In [45]:
x[2]  #a list (row in matrix)

['g', 'h', 'i']

#### appending new elments

In [46]:
x=['a','b'] 
x = x + ['c', 'd']
x

['a', 'b', 'c', 'd']

In [47]:
del(x[1]) #delete 2nd element in the list
x

['a', 'c', 'd']

#### list references and list copies

In [48]:
x=[1,2]
y=x   # y is a reference to x
x[0]=-1 #so when a data under x changes
y  # the referenced data is changed as well ( 1 copy in memor)

[-1, 2]

In [49]:
z=list(x) # making an explicit copy of x in memory
x[0]= -2  
z  # z is independent from x

[-1, 2]

## Functions

In [50]:
round(1.68, 1)

1.7

In [51]:
help(round)

Help on built-in function round in module builtins:

round(...)
    round(number[, ndigits]) -> number
    
    Round a number to a given precision in decimal digits (default 0 digits).
    This returns an int when called with one argument, otherwise the
    same type as the number. ndigits may be negative.



In [52]:
?max #inline help

In [53]:
first = [11.25, 18.0, 20.0]
sorted(first, reverse=True) #sort a list in a reverse order

[20.0, 18.0, 11.25]

### methods

In [54]:
first.append(30.33)
first

[11.25, 18.0, 20.0, 30.33]

In [55]:
first.index(20.0)

2

In [56]:
pdesc="poolhouse"

In [57]:
pdesc.upper()

'POOLHOUSE'

In [58]:
pdesc.count('o')

3

In [59]:
first.remove(11.25) # change first
first

[18.0, 20.0, 30.33]

In [60]:
first.reverse() #change first
first

[30.33, 20.0, 18.0]

In [61]:
print(len(first)) #length of an array

3


## how to check variables at current stack

In [62]:
whos

Variable     Type     Data/Info
-------------------------------
crit         bool     True
desc         str      compound interest
factor       float    1.1
fam          list     n=5
fam2         list     n=3
first        list     n=3
l            list     n=3
nyears       int      7
pdesc        str      poolhouse
profitable   bool     True
result       float    194.87171000000012
savings      int      100
x            list     n=2
y            list     n=2
z            list     n=2


## Packages

pkg/
    module1.py
    module2.py

use pip tool to install package  

ex %>pip3 install numpy

In [63]:
import numpy  as np # to import a package with a short prefix name

In [64]:
np.array([1,2,3]) # prefix is used

array([1, 2, 3])

In [65]:
from numpy import array #import a specific function from package , use with no prefix

In [66]:
array([4,5,6])

array([4, 5, 6])

In [67]:
import math

In [68]:
radius=2.0
circ_air=math.pi * radius**2
circ_air

12.566370614359172

### Numpy package (numeric python)

In [69]:
np_height=np.array([1.73,1.68]) #numpy arrays contain only one time
np_weight=np.array([65.4,59.2])
bmi=np_weight / np_height **2   # operation performed on each element of lists in the formula
bmi

array([ 21.85171573,  20.97505669])

In [70]:
bmi[bmi > 21.0]

array([ 21.85171573])

### 2D  numpy arrays

In [71]:
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])

In [72]:
np_mat[0,:] #access top row

array([1, 2])

In [73]:
np_mat[-1,:] #access bottow row

array([5, 6])

In [74]:
np_mat[:,0] #access the first column

array([1, 3, 5])

In [75]:
np_mat[:,1] #access of the 2nd column

array([2, 4, 6])

In [76]:
np_mat + 10 #add to each element 10

array([[11, 12],
       [13, 14],
       [15, 16]])

In [77]:
np_mat + np.array([10,10]) #same result as above

array([[11, 12],
       [13, 14],
       [15, 16]])

In [78]:
np_mat**2  ## multiply each element by itself

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

In [79]:
np_mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [80]:
np_mat * np.array([2,3]) # multiply each row in array by a second array element by element

array([[ 2,  6],
       [ 6, 12],
       [10, 18]])

### Basic status on numpy arrays

In [81]:
height = np.round(np.random.normal(1.75, 0.20, 5000),2) # generate an array from  normal dist
# 1.75 is mean, 0.20 is stdev 5000 is number of samples

In [82]:
np.mean(height)


1.7503099999999998

In [83]:
np.median(height)

1.74

In [84]:
np.std(height)

0.20237253741552977

In [85]:
np.sort(height) # sorts all elements

array([ 1.07,  1.07,  1.07, ...,  2.39,  2.39,  2.41])

In [86]:
np.sum(height) #sums elements

8751.5499999999993

#### how to colbind two columns in array

In [87]:
weight = np.round(np.random.normal(60.32, 15, 5000),2)

In [88]:
np_city = np.column_stack((height,weight))

In [89]:
np_city

array([[  1.45,  61.24],
       [  1.58,  88.49],
       [  2.11,  48.35],
       ..., 
       [  1.64,  44.05],
       [  1.58,  33.49],
       [  1.77,  56.  ]])

### subsetting np arrays

In [90]:
categ = np.array(['B', 'G', 'B', 'G', 'B']) # a group of boys and girls

In [91]:
height = np.array([170, 165, 164, 166, 172]) # their respective height

In [92]:
categ=='B'  ## this makes an index selecting only boys

array([ True, False,  True, False,  True], dtype=bool)

In [93]:
height[categ=='B'] ## heighs of only boys

array([170, 164, 172])

In [94]:
np.median(height[categ=='B']) #median of boys height

170.0

In [95]:
np.median(height[categ=='G']) ## median of girls height

165.5

#### this finishes the datacamp course Introduction to Python